<?
//****************************************************************************
//*     This file was generated by the fishCMS installer.
//*     PLEASE DO NOT EDIT THE CONTENTS OF THIS FILE UNLESS YOU ARE 100% SURE!
//****************************************************************************
$db_type='pgsql';
$db_host='localhost';
$db_username='fishcms';
$db_password='';
$db_database='fishcms';
$list_prefix='FishCMS6_';
?>
