<?
//****************************************************************************
//*     This file was generated by the fishCMS installer.
//*     PLEASE DO NOT EDIT THE CONTENTS OF THIS FILE UNLESS YOU ARE 100% SURE!
//****************************************************************************
$db_host="localhost";
$db_username="believewithus";
$db_password="j8xc0D875";
$db_database="believewithus";
$list_prefix="FishCMS_";
?>
